#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: 250a666
#
Name     : R-warp
Version  : 0.2.1
Release  : 24
URL      : https://cran.r-project.org/src/contrib/warp_0.2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/warp_0.2.1.tar.gz
Summary  : Group Dates
Group    : Development/Tools
License  : MIT
Requires: R-warp-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
yearly, monthly, by second, by week of the month, and more.  The
    groups are defined in such a way that they also represent the distance
    between dates in terms of the period. This extracts valuable
    information that can be used in further calculations that rely on a
    specific temporal spacing between observations.

%package lib
Summary: lib components for the R-warp package.
Group: Libraries

%description lib
lib components for the R-warp package.


%prep
%setup -q -n warp
pushd ..
cp -a warp buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1698964699

%install
export SOURCE_DATE_EPOCH=1698964699
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/warp/DESCRIPTION
/usr/lib64/R/library/warp/INDEX
/usr/lib64/R/library/warp/LICENSE
/usr/lib64/R/library/warp/Meta/Rd.rds
/usr/lib64/R/library/warp/Meta/features.rds
/usr/lib64/R/library/warp/Meta/hsearch.rds
/usr/lib64/R/library/warp/Meta/links.rds
/usr/lib64/R/library/warp/Meta/nsInfo.rds
/usr/lib64/R/library/warp/Meta/package.rds
/usr/lib64/R/library/warp/Meta/vignette.rds
/usr/lib64/R/library/warp/NAMESPACE
/usr/lib64/R/library/warp/NEWS.md
/usr/lib64/R/library/warp/R/warp
/usr/lib64/R/library/warp/R/warp.rdb
/usr/lib64/R/library/warp/R/warp.rdx
/usr/lib64/R/library/warp/doc/hour.R
/usr/lib64/R/library/warp/doc/hour.Rmd
/usr/lib64/R/library/warp/doc/hour.html
/usr/lib64/R/library/warp/doc/index.html
/usr/lib64/R/library/warp/help/AnIndex
/usr/lib64/R/library/warp/help/aliases.rds
/usr/lib64/R/library/warp/help/paths.rds
/usr/lib64/R/library/warp/help/warp.rdb
/usr/lib64/R/library/warp/help/warp.rdx
/usr/lib64/R/library/warp/html/00Index.html
/usr/lib64/R/library/warp/html/R.css
/usr/lib64/R/library/warp/tests/testthat.R
/usr/lib64/R/library/warp/tests/testthat/helper-constructor.R
/usr/lib64/R/library/warp/tests/testthat/helper-with-option.R
/usr/lib64/R/library/warp/tests/testthat/test-boundaries.R
/usr/lib64/R/library/warp/tests/testthat/test-change.R
/usr/lib64/R/library/warp/tests/testthat/test-date.R
/usr/lib64/R/library/warp/tests/testthat/test-distance.R
/usr/lib64/R/library/warp/tests/testthat/test-divmod.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/warp/libs/warp.so
/usr/lib64/R/library/warp/libs/warp.so.avx2
/usr/lib64/R/library/warp/libs/warp.so.avx512
